all:
	as -gstabs -o guilhermepedroso_automatoipv4_linguagemdemontagem.o guilhermepedroso_automatoipv4_linguagemdemontagem.s
	ld -o guilhermepedroso_automatoipv4_linguagemdemontagem guilhermepedroso_automatoipv4_linguagemdemontagem.o

clean:
	rm -vf *.o guilhermepedroso_validaip
